; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:parte1_1]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte1_1

[env:parte1_2]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte1_2

[env:parte2_1]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte2_1

[env:parte2_2]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte2_2

[env:parte2_3]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte2_3

[env:parte3_1]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte3_1

[env:parte3_2a]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte3_2a

[env:parte3_2b]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte3_2b

[env:parte3_3a]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte3_3a

[env:parte3_3b]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte3_3b

[env:parte3_3c]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=parte3_3c