#include "examen.h"

//APARTADO 1 ALMACENAR EN LA VARIABLE RESULT EL NUMERO DE NUMEROS POSITIVOS QUE HAY EN EL VECTOR DE FORMA RECUSIVA.
void apartado1(int * VECTOR, int nEle, int * result)
{
    
}

//APARTADO 2 INVERTIR LOS ELEMENTOS DEL VECTOR DE FORMA RECURSIVA.
void apartado2(int * VECTOR, int nEle)
{
    
}

//COMPLETAR CON LAS FUNCIONES QUE HAYAS IMPLEMENTADO


//