inicio: saludo compilar

saludo:
	@echo Bienvenido al makefile de Alejandro Gómez Amaro

compilar: main.o funciones.o
	gcc -Wall main.o funciones.o -o ejercicio.exe

main.o:
	gcc -c main.c

funciones.o:
	gcc -c funciones.c