; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:polling]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=polling
[env:interrupt]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.cmake_extra_args = -D MODE=interrupt
